### ISSUE TITLE
Malformed Rendering in Addresses API Documentation

### ISSUE THREAD

**Issue by Mohammed90** [monicahq/marketing_site#46]
The following particular line is not rendered properly:
https://github.com/monicahq/marketing_site/blame/0d98f15ba920a8ca358d10f58808a876403371f6/api_documentation/addresses.md#L223

You can see it here:
https://github.com/monicahq/marketing_site/blob/0d98f15ba920a8ca358d10f58808a876403371f6/api_documentation/addresses.md#L223

**Comment by asbiin** [comment]
Fixed
